### ISSUE TITLE
2024-10-31  全局css 方案设计

### ISSUE THREAD

**Issue by yxiZo** [yxiZo/blog#35]
## 简介
前端项目中不可避免会需要编写一些全局的css 样式, 这里来说明一下有哪些css属性, 以及为什么要这些属性
例如
```css
*,
::before,
::after {
  ...
}

::backdrop{
  ...
}

@font-face {
  font-family: "Mabry Pro";
  src: url(https://assets.gumroad.com/packs/static/19db990205089207b039.woff2);
}

:root,
:host {
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
    :root,
    :host {
      --body-bg: #242423;
      --primary: 221 221 221;
      --contrast-primary: 0 0 0;
      --color: 221 221 221;
      --filled: 0 0 0;
      --contrast-filled: 221 221 221;
      --contrast-black: 221 221 221;
      --border-alpha: 0.35;
    }
}

html,
body {
  ...
}

body {
  font-size: 1rem;
  line-height: 1.4;
  font-family: var(--font-family);
  background-color: var(--body-bg);
  -webkit-font-smoothing: antialiased;
  color: rgb(var(--color));
}
body:not(.mac) *::-webkit-scrollbar {
  width: .75rem;
  background-color: rgb(var(--color)/0.1);
}
body:not(.mac) *::-webkit-scrollbar-thumb {
  background-color: rgb(var(--color)/0.5);
  border-radius: .5rem;
}


.container {
  width: 100%;
}
@media (min-width: 640px) {
  .container {
    max-width: 640px;
  }
}
@media (min-width: 768px) {
  .container {
    max-width: 768px;
  }
}
@media (min-width: 1024px) {
  .container {
    max-width: 1024px;
  }
}
@media (min-width: 1280px) {
  .container {
    max-width: 1280px;
  }
}
@media (min-width: 1536px) {
  .container {
    max-width: 1536px;
  }
}

.img-fluid {
  max-width: 100%;
  height: auto;
}



body:not(.mac) *::-webkit-scrollbar {
  width: 0.75rem;
  background-color: rgb(var(--color) / 0.1);
}
body:not(.mac) *::-webkit-scrollbar-thumb {
  background-color: rgb(var(--color) / 0.5);
  border-radius: 0.5rem;
}
body:not(.mac) *::-webkit-scrollbar-track {
    background: #fff;
}
```

## 全局css变量
自从web 原生支持css变量后, 前端再也不用使用各类css预处理器才能使用变量来书写css了,  接下来看一下一般全局的css变量应当有哪些, 以及它们分别的作用是什么

通常全局css变量应当放置再最顶层的元素上, 这样后续元素通过css的层叠属性可以轻松覆盖变量值
使用伪类 :root  :host

```css
:root {
   color-scheme: light dark;
  // 预定义颜色
  --pink: #ff90e8;
  --purple: #90a8ed;
  --green: #23a094;
  --orange: #ffc900;
  --red: #dc341e;
  --yellow: #f1f333;
  --primary: 255,255,255
}
```
1. 颜色
颜色方案-业内
chakraUI -color
shadcn/ui
radix-ui

调色板  palette

概念
- Accent  强调色或辅助色
- Backgroud 背景色
- grey 灰度
- contrast 对比度

https://zhuanlan.zhihu.com/p/32422584
